[2025-10-21T00:27:47.163+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: harshitha_lab3_kmeans_live.compute_sse_and_silhouette manual__2025-10-21T00:27:37.585255+00:00 [queued]>
[2025-10-21T00:27:47.171+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: harshitha_lab3_kmeans_live.compute_sse_and_silhouette manual__2025-10-21T00:27:37.585255+00:00 [queued]>
[2025-10-21T00:27:47.171+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-21T00:27:47.171+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-10-21T00:27:47.171+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-21T00:27:47.184+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): compute_sse_and_silhouette> on 2025-10-21 00:27:37.585255+00:00
[2025-10-21T00:27:47.202+0000] {standard_task_runner.py:55} INFO - Started process 918 to run task
[2025-10-21T00:27:47.206+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'harshitha_lab3_kmeans_live', 'compute_sse_and_silhouette', 'manual__2025-10-21T00:27:37.585255+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/***_lab3_live.py', '--cfg-path', '/tmp/tmpwn9vo1xa']
[2025-10-21T00:27:47.210+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask compute_sse_and_silhouette
[2025-10-21T00:27:47.255+0000] {task_command.py:388} INFO - Running <TaskInstance: harshitha_lab3_kmeans_live.compute_sse_and_silhouette manual__2025-10-21T00:27:37.585255+00:00 [running]> on host dadf5dcd63e0
[2025-10-21T00:27:47.327+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=harshitha
AIRFLOW_CTX_DAG_ID=harshitha_lab3_kmeans_live
AIRFLOW_CTX_TASK_ID=compute_sse_and_silhouette
AIRFLOW_CTX_EXECUTION_DATE=2025-10-21T00:27:37.585255+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-21T00:27:37.585255+00:00
[2025-10-21T00:27:47.330+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/live.py", line 69, in build_save_model
    km.fit(Xs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1146, in fit
    self._check_params(X)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 937, in _check_params
    if self.n_init <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
[2025-10-21T00:27:47.338+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=harshitha_lab3_kmeans_live, task_id=compute_sse_and_silhouette, execution_date=20251021T002737, start_date=20251021T002747, end_date=20251021T002747
[2025-10-21T00:27:47.348+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task compute_sse_and_silhouette ('<=' not supported between instances of 'str' and 'int'; 918)
[2025-10-21T00:27:47.386+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-21T00:27:47.407+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
